openapi: 3.0.0
info:
  title: My First API
  version: "0.1"
servers:
- url: /
paths:
  /v1/products:
    get:
      operationId: 34ee6e9e8fa0c95d9bd89cfc374a81e2
      responses:
        "200":
          $ref: '#/components/schemas/Product'
      summary: Retorna uma lista dos produtos
      x-accepts: application/json
  /v1/search?q={q}:
    get:
      operationId: search
      parameters:
      - description: Parâemtro utilizado no filtro, pode ser o nome ou código do produto
        explode: true
        in: query
        name: q
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          $ref: '#/components/schemas/Product'
      summary: Retorna uma lista dos produtos filtrados pelo parâmetro passado
      x-accepts: application/json
components:
  schemas:
    Product:
      description: Product model
      title: Product
      type: Illuminate\Database\Eloquent\Model

